language: python

services:
  - docker

python:
  - "2.7"

before_install:
  - docker build -t lloydie/hello-docker .
  - docker run -d -p 127.0.0.1:80:4567 lloydie/hello-docker
  - docker ps -a

install:
  - pip install -r requirements.txt

script:
  - pytest test.py

after_success:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push lloydie/hello-docker
