#!/bin/bash

Docker-container() {
    docker run -it \
	--name=hello-docker \
	lloydie/hello-docker:latest
}

Docker-swarm() {
    docker stack deploy -c docker-compose.yml hello-docker
}

Docker-machines() {
    export VIRTUALBOX_BOOT2DOCKER_URL=file://$HOME/.docker/machine/cache/boot2docker-18.06.1-ce.iso

    SWARM_MANAGERS=2
    SWARM_WORKERS=2

    # create manager machines
    for node in $(seq 1 $SWARM_MANAGERS); do
	docker-machine create --driver virtualbox manager.$node
	docker-machine ssh manager.$node "mkdir ./data"
    done

    # create worker machines
    for node in $(seq 1 $SWARM_WORKERS); do
	docker-machine create --driver virtualbox worker.$node
    done

    # Initialize swarm and create manager
    docker-machine ssh manager.1 "docker swarm init --listen-addr $(docker-machine ip manager.1) --advertise-addr $(docker-machine ip manager.1)"

    # get manager and worker tokens
    export manager_token=`docker-machine ssh manager.1 "docker swarm join-token manager -q"`
    export worker_token=`docker-machine ssh manager.1 "docker swarm join-token worker -q"`

    # other masters join swarm
    for node in $(seq 2 $SWARM_MANAGERS);
    do
	    docker-machine ssh manager.$node \
		    "docker swarm join \
		    --token $manager_token \
		    --listen-addr $(docker-machine ip manager.$node) \
		    --advertise-addr $(docker-machine ip manager.$node) \
		    $(docker-machine ip manager.1)"
    done

    # workers join swarm
    for node in $(seq 1 $workers);
    do
	    docker-machine ssh worker.$node \
	    "docker swarm join \
	    --token $worker_token \
	    --listen-addr $(docker-machine ip worker.$node) \
	    --advertise-addr $(docker-machine ip worker.$node) \
	    $(docker-machine ip manager.1)"
    done

}

docker-swarm() {
    PKG_PATH=$(pwd)
    PKG_NAME=${PKG_PATH##*/}
    docker swarm init
    docker stack deploy -c docker-compose.yml "$PKG_NAME"
}
