version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: lloydie/hello-docker:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:

